### PR TITLE
benchmark_runner/workloads/workloads_operations.py: fix typo introduced in #394

### PR DESCRIPTION
**Pull request by kpouget**
```
  File "/usr/local/lib/python3.9/site-packages/benchmark_runner/workloads/workloads_operations.py", line 57, in __init__
    es_url_protocol=self.es_url_protocol,
AttributeError: 'Workloads' object has no attribute 'es_url_protocol'
```

### CODE REVIEW

**Comment by ebattat** [comment]
@kpouget,
Need to add the same in benchmark-operator operations:
https://github.com/redhat-performance/benchmark-runner/blob/main/benchmark_runner/benchmark_operator/benchmark_operator_workloads_operations.py
```
        self._es_url_protocol = self._environment_variables_dict['elasticsearch_url_protocol']
        self._ssh = SSH()
        # Elasticsearch connection
        if self._es_host and self._es_port:
            self.__es_operations = ElasticSearchOperations(es_host=self._es_host,
                                                           es_port=self._es_port,
                                                           es_user=self._es_user,
                                                           es_password=self._es_password,
                                                           es_url_protocol=self._es_url_protocol,
                                                           timeout=self._timeout)
```

**Comment by ebattat** [comment]
@kpouget , due to the e2e failed, no auto bumb version, need to progress the tag version manually:
https://github.com/redhat-performance/benchmark-runner/blob/main/setup.py - 314
https://github.com/redhat-performance/benchmark-runner/blob/main/.bumpversion.cfg - 314
